name: Quality Assurance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  functional_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Test with Gradle
        run:  ./gradlew test jacocoTestReport
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
          flags: unittests